baseurl = "https://www.danewilliams.me"
title = "danewilliams.me"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

#publish to docs directory for compatibility with github pages
publishDir = "docs/"

[params]
    author = "Dane Williams"
    info = "Computer Science Undergrad at Notre Dame"
    description = "Dane Williams' Personal Website"
    keywords = "developer,student,blog"
    avatarurl = "/images/DaneWilliamsHeadshot.jpg"

	#favicon_32 = "/img/favicon-32x32.png"
	#favicon_16 = "/img/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false
	since = 2020

    rtl = false

	colorscheme = "dark"

	#math = true
	#custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/danerwilliams/"
[[params.social]]
	name = "LinkedIn"
	icon = "fab fa-linkedin"
	weight = 2
	url = "https://linkedin.com/in/danerwilliams/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 3
    url = "https://gitlab.com/dwilli36/"
[[params.social]]
	name = "Resume"
	icon = "far fa-file"
	weight = 4
	url = "https://github.com/danerwilliams/resume/blob/master/DaneWilliamsResume.pdf"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "posts/"
[[menu.main]]
	name = "Projects"
	weight = 3
	url = "projects/"
[[menu.main]]
	name = "Contact"
	weight = 4
	url = "contact/"
